matrix:
  include:
  - language: c
    sudo: enabled
    before_install:
      - sudo apt-get update
      - sudo apt-get install -y gfortran liblapack-dev cmake
      - pip install numpy --user
    install:
      - mkdir build
      - cd build
    script:
      - sudo apt-get install -y libopenmpi-dev openmpi-bin
      - cmake -DTesting=ON ../
      - make
      - export OMP_NUM_THREADS=1
      - make test MPIRUN="mpiexec -np 4"
      - rm -r test
      - make
      - export OMP_NUM_THREADS=3
      - make test MPIRUN="mpiexec -np 4"
      - rm -r test
      - make
  - os: osx
    language: c
    sudo: enabled
    # "_stdio.h: No such file or directory", when building samtools.
    softwareupdate --list
    softwareupdate --install "Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4"
    before_install:
      - brew update
      - brew install gcc-7 || true
      - brew install lapack
      
install:
      - mkdir build
      - cd build
    script:
      - cmake -DTesting=ON -DCONFIG=gcc -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_Fortran_COMPILER=gfortran-7 ../
      - make
      - export OMP_NUM_THREADS=1
      - make test
