matrix:
  include:
  - language: c
    sudo: enabled
    before_install:
      - sudo apt-get update
      - sudo apt-get install -y gfortran liblapack-dev cmake
      - pip install numpy --user
    install:
      - mkdir build
      - cd build
    script:
      - sudo apt-get install -y libopenmpi-dev openmpi-bin
      - cmake -DTesting=ON ../
      - make
      - export OMP_NUM_THREADS=1
      - make test MPIRUN="mpiexec -np 4"
      - rm -r test
      - make
      - export OMP_NUM_THREADS=3
      - make test MPIRUN="mpiexec -np 4"
      - rm -r test
      - make
  - os: osx
    language: c
    sudo: enabled
    before_install:
      - brew update
      - brew install --with-toolchain llvm
      - brew install lapack
      - export FC=gfortran;
      - export CC := clang
    install:
      - mkdir build
      - cd build
    script:
      - cmake -DTesting=ON ../
      - make
      - export OMP_NUM_THREADS=1
      - make test
